//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project5.VanessaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VanessaService.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/YTurls", ReplyAction="http://tempuri.org/IService2/YTurlsResponse")]
        string YTurls(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/YTurls", ReplyAction="http://tempuri.org/IService2/YTurlsResponse")]
        System.Threading.Tasks.Task<string> YTurlsAsync(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/YTdescription", ReplyAction="http://tempuri.org/IService2/YTdescriptionResponse")]
        string YTdescription(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/YTdescription", ReplyAction="http://tempuri.org/IService2/YTdescriptionResponse")]
        System.Threading.Tasks.Task<string> YTdescriptionAsync(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/YTtitle", ReplyAction="http://tempuri.org/IService2/YTtitleResponse")]
        string YTtitle(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/YTtitle", ReplyAction="http://tempuri.org/IService2/YTtitleResponse")]
        System.Threading.Tasks.Task<string> YTtitleAsync(string query);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : Project5.VanessaService.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<Project5.VanessaService.IService2>, Project5.VanessaService.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string YTurls(string query) {
            return base.Channel.YTurls(query);
        }
        
        public System.Threading.Tasks.Task<string> YTurlsAsync(string query) {
            return base.Channel.YTurlsAsync(query);
        }
        
        public string YTdescription(string query) {
            return base.Channel.YTdescription(query);
        }
        
        public System.Threading.Tasks.Task<string> YTdescriptionAsync(string query) {
            return base.Channel.YTdescriptionAsync(query);
        }
        
        public string YTtitle(string query) {
            return base.Channel.YTtitle(query);
        }
        
        public System.Threading.Tasks.Task<string> YTtitleAsync(string query) {
            return base.Channel.YTtitleAsync(query);
        }
    }
}
